export let text = {
    p1: "Immagina una fighissima home page",
    p2: "In caso di difficolta, farsi di _ _ _ _ (inserire il suo prodotto preferito)<br> e riprendere il divertimento",
    p3: "Immagina una fighissima raccolta giochi",
    p4: "Pong Locale: 2 - 4 Giocatori",
    p5: "Immagina un Form migliore e Registrati",
    p6: "Nome",
    p7: "Converma Password",
    p8: "Registrati",
    p9: "Hai un account? Accedi qui",
    p10: "Immagina un Form migliore e Accedi",
    p11: "Accedi",
    p12: "Non hai un account? Registrati qui",
    p13: "Immagina un Form migliore e<br>Inserisci il codice inviato nella mail",
    p14: "Codice OTP",
    p15: "Invia",
    p16: "Freccia alto",
    p17: "Numero dei giocatori: ",
    p18: "Avanti",
    p19: "Torna indietro",
    p20: "I nomi non possono essere vuoti",
    p21: "I nomi dei giocatori devo essere diversi",
    p22: "Premi [Spazio] per iniziare",
    p23: "Persolalizza il gioco",
    p24: "Modalita",
    p25: "Classico",
    p26: "Inizia",
    p27: "Tempo della partita: ",
    p28: " minuti",
    p29: "Velocita di movimento: ",
    p30: "Immagine una bellissima pagina: 404 Risorsa non trovata",
    p31: "Torna al fantastico elenco giochi",
    p32: "Vittoria per ",
    p33: "Pareggio",
    p34: "Freccia basso",
    p35: "",
    p36: "",
    p37: "",
    p38: "",
    p39: "",
    // p0: "",
    // p1: "",
    // p2: "",
    // p3: "",
    // p4: "",
    // p5: "",
    // p6: "",
    // p7: "",
    // p8: "",
    // p9: "",
};